import React from 'react';
import { createRoot } from 'react-dom/client';
import { Booth, Pickup } from './Booth';
import { Admin } from './Admin';
import './styles.css';
import './editorial.css';
import './theme-gallery.css';
import './generation-preview.css';
import './studio-polish.css';
import './page-motion.css';
import './photo-frame.css';
import './photo-library.css';
import './booth-flow.css';
import './studio-refresh.css';
import './admin-workspace.css';
import './kiosk-touch.css';
const path = location.pathname;
createRoot(document.getElementById('root')!).render(path.startsWith('/pickup/') ? <Pickup /> : path === '/admin' ? <Admin /> : <Booth />);
